package com.helpdesk.service.rag;

import java.util.List;

/**
 * Abstraction for generating dense vector embeddings from text.
 * Implementations query embedding models (e.g. HuggingFace, OpenAI, Cohere, or local models).
 */
public interface EmbeddingService {

    /**
     * Converts a text string into a float vector array representation.
     *
     * @param text String input to be embedded
     * @return float array representing the semantic embedding vector
     */
     float[] embedText(String text);

    /**
     * Converts a batch of text strings into a list of float vector arrays.
     *
     * @param texts List of text strings to embed
     * @return List of float arrays representing semantic vectors
     */
    List<float[]> embedBatch(List<String> texts);

    /**
     * Returns the dimension size of vectors generated by this service (e.g. 384 for all-MiniLM-L6-v2).
     */
    int getDimension();

    /**
     * Returns the model name used by this service.
     */
    String getModelName();
}
